name: Tests

on:
  pull_request:
    branches: [develop]
    paths:
      - "primer-steps/**"

defaults:
  run:
    working-directory: primer-steps

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run test suite
        run: yarn test
